version: '3'

services:
  db-node-1:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: db-node-1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sql_test
      MYSQL_USER: test
      MYSQL_PASSWORD: pzjqUkMnc7vfNHET
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - my_network
    ports:
      - 3306:3306
    volumes:
      - db-node-1-data:/var/lib/mysql

  sql_test:
      container_name: sql_test_main
      image: ddzuba/sql_test
      command: db-node-1
      networks:
        - my_network
      depends_on:
      - "db-node-1"

volumes:
  db-node-1-data:

networks:
  my_network:
    driver: bridge

