version: '3'

services:
  apache:
    image: httpd:2.4
    ports:
      - 8080:80
    volumes:
      - /Users/dvdemon/OneDrive/Documents/Lectures/PPS/2021/Materials/Docker/Example02:/usr/local/apache2/htdocs